# Generated by Django 4.2.6 on 2023-11-12 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_comment='Quantity sold', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SouvenirSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_comment='Quantity sold', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('unitary_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_comment='Quantity sold', max_length=3)),
                ('promotion_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promotion_description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method_of_payment', models.CharField(choices=[('CA', 'Cash'), ('DB', 'Debit card'), ('CC', 'Credit card'), ('CQ', 'Cheque'), ('BT', 'Bank transfer')], default='CA', max_length=2)),
                ('currency', models.CharField(choices=[('USD', 'American Dollars'), ('BOB', 'Bolivianos')], default='BOB', max_length=3)),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expenditure')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('donor_last_name', models.CharField(max_length=30)),
                ('donor_name', models.CharField(max_length=30)),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='FoodSale',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='SouvenirSale',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='VolunteerPayment',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            bases=('transactions.transaction',),
        ),
    ]
