# Generated by Django 4.2.6 on 2023-11-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(db_comment='User who registered the transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsaledetail',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type', to='transactions.systemtype'),
        ),
        migrations.AddField(
            model_name='systemtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='transactions.systemtypecategory'),
        ),
        migrations.AddField(
            model_name='souvenirsaledetail',
            name='souvenir_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenir_type', to='transactions.systemtype'),
        ),
        migrations.AddField(
            model_name='foodsaledetail',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='transactions.systemtype'),
        ),
        migrations.AddField(
            model_name='volunteerpayment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsaledetail',
            name='ticket_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sale', to='transactions.ticketsale'),
        ),
        migrations.AddField(
            model_name='souvenirsaledetail',
            name='souvenir_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souvenir_sale', to='transactions.souvenirsale'),
        ),
        migrations.AddField(
            model_name='foodsaledetail',
            name='food_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_sale', to='transactions.foodsale'),
        ),
    ]
