# Generated by Django 4.2.6 on 2023-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsaledetail',
            name='quantity',
            field=models.IntegerField(db_comment='Quantity sold'),
        ),
        migrations.AlterField(
            model_name='souvenirsaledetail',
            name='quantity',
            field=models.IntegerField(db_comment='Quantity sold'),
        ),
        migrations.AlterField(
            model_name='ticketsaledetail',
            name='quantity',
            field=models.IntegerField(db_comment='Quantity sold'),
        ),
    ]
